traj0:
  - positions: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    velocities: [0, 0, 0, 0, 0, 0]
    time_from_start:
      sec: 4
      nanosec: 0
  - positions: [0.0, 0.0, 0.0, 0.5, 0.5, 0.0]
    velocities: [0, 0, 0, 0, 0, 0]
    time_from_start:
      sec: 8
      nanosec: 0

traj1:
  - positions: [0.0, 1.0, 0.5, 0.0, 1.2, -0.5]
    velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    time_from_start:
      sec: 1
      nanosec: 0
  - positions: [0.1, 1.1, 0.6, 0.1, 1.3, -0.6]
    velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    time_from_start:
      sec: 2
      nanosec: 0